window.EDSA_QUESTION_BANKS={
 dme:[
  {t:'SEO',what:'Improving a website’s visibility in unpaid search results.',why:'It helps people discover relevant pages through search engines.',action:'Match useful content to search intent and optimize important on-page elements.',signal:'Organic search traffic, rankings, impressions, and clicks.',scenario:'A page receives impressions but few clicks, so review its title and search-result relevance.'},
  {t:'Google Ads',what:'A paid advertising platform for reaching users across Google properties.',why:'It can put relevant offers in front of people actively searching or browsing.',action:'Choose a relevant campaign objective, audience, budget, and conversion goal.',signal:'Clicks, conversions, cost per conversion, and return on ad spend.',scenario:'An ad gets clicks but no sales, so inspect the landing page and conversion tracking before raising spend.'},
  {t:'Email Marketing',what:'Using email to communicate relevant information or offers to subscribers.',why:'It provides a direct channel for nurturing relationships and encouraging action.',action:'Segment subscribers and send useful, permission-based messages with clear calls to action.',signal:'Delivery, clicks, conversions, unsubscribes, and other meaningful engagement metrics.',scenario:'A campaign has low engagement, so test the subject line, audience segment, timing, and message relevance.'},
  {t:'Conversion Funnels',what:'A model showing stages from awareness through consideration, conversion, and retention.',why:'It helps marketers identify where potential customers drop out.',action:'Measure each stage and improve the experience at the largest meaningful drop-off.',signal:'Stage-to-stage conversion rates and completed goal actions.',scenario:'Many visitors reach checkout but few purchase, so investigate friction at checkout rather than only increasing traffic.'},
  {t:'Content Strategy',what:'A planned approach to creating and distributing content for defined audiences and goals.',why:'It keeps content aligned with business objectives and audience needs.',action:'Define audience, objectives, content pillars, formats, channels, and measurement.',signal:'Reach, engagement, qualified traffic, leads, and conversions tied to content goals.',scenario:'Posts are frequent but inconsistent, so establish content pillars and a publishing plan.'},
  {t:'Social Media Marketing',what:'Using social platforms to communicate with audiences and support marketing objectives.',why:'Social channels can build awareness, relationships, traffic, and community.',action:'Adapt content to each platform while monitoring audience response.',signal:'Reach, engagement, clicks, leads, conversions, and community response.',scenario:'One post format performs poorly on a platform, so test a format suited to that platform’s audience behavior.'},
  {t:'Analytics',what:'Collecting and interpreting data about digital activity and outcomes.',why:'It turns activity data into evidence for better marketing decisions.',action:'Define useful metrics, verify tracking, compare results, and act on findings.',signal:'Accurate traffic, event, conversion, and campaign-source data.',scenario:'Reports disagree, so first audit tracking definitions and data collection before changing strategy.'},
  {t:'Audience Targeting',what:'Selecting and reaching people who are relevant to a campaign or offer.',why:'Relevance can improve message fit and reduce wasted marketing effort.',action:'Use research and appropriate audience criteria instead of assuming everyone is the same.',signal:'Audience quality, engagement, conversion rate, and acquisition cost.',scenario:'A campaign reaches many people but few prospects, so refine the audience around relevant needs and intent.'},
  {t:'Marketing KPIs',what:'Key measurable indicators connected to important marketing objectives.',why:'They keep performance evaluation focused on outcomes that matter.',action:'Choose a small set of measurable indicators linked to defined objectives.',signal:'Objective-specific metrics such as conversions, qualified leads, retention, or revenue.',scenario:'A team celebrates impressions while sales fall, so add KPIs that reflect the actual business objective.'},
  {t:'Digital Campaign Planning',what:'Structuring goals, audiences, messages, channels, budgets, timing, and measurement before launch.',why:'Planning reduces disconnected activity and makes results easier to evaluate.',action:'Write a measurable objective and define audience, offer, channel plan, budget, and tracking.',signal:'Progress against objectives, budget, reach, engagement, and conversion results.',scenario:'A campaign launches without tracking, so establish measurable goals and tracking before relying on performance data.'}
 ],
 pbm:[
  {t:'Project Scope',what:'The defined boundaries of what a project will and will not deliver.',why:'Clear scope reduces misunderstandings and uncontrolled additions.',action:'Document deliverables, exclusions, assumptions, and acceptance criteria.',signal:'Approved scope, requirements, deliverables, and change requests.',scenario:'A stakeholder asks for an extra feature, so check it against the approved scope before committing.'},
  {t:'Agile Methods',what:'An iterative approach that delivers work in small increments and uses feedback frequently.',why:'Frequent feedback can help teams adapt to changing needs.',action:'Prioritize valuable work, deliver increments, review results, and adjust the backlog.',signal:'Working increments, feedback, backlog progress, and cycle or sprint outcomes.',scenario:'Requirements change during development, so reprioritize upcoming work rather than ignoring the new information.'},
  {t:'Risk Management',what:'The process of identifying, assessing, responding to, and monitoring project risks.',why:'Early risk handling can reduce threats to objectives.',action:'Record risks, assess probability and impact, assign owners, and plan responses.',signal:'Risk exposure, response status, owners, and newly identified risks.',scenario:'A key supplier may delay delivery, so assess the risk and prepare an appropriate response before the deadline.'},
  {t:'Gantt Charts',what:'A timeline view showing project tasks, durations, and planned sequencing.',why:'It helps teams visualize timing and dependencies.',action:'Map tasks to dates, durations, milestones, and dependencies.',signal:'Planned versus actual dates and progress of scheduled tasks.',scenario:'A dependent task cannot start on time, so review the predecessor relationship and update the schedule.'},
  {t:'Stakeholder Management',what:'Identifying stakeholders and managing communication and engagement with them.',why:'Different stakeholders have different interests, influence, and information needs.',action:'Map stakeholders by influence and interest and tailor communication accordingly.',signal:'Stakeholder concerns, decisions, engagement, and unresolved issues.',scenario:'A high-influence stakeholder is surprised by a change, so improve the communication plan and decision visibility.'},
  {t:'Business Planning',what:'Defining business objectives, resources, actions, and measures for achieving intended results.',why:'A plan connects activities and resources to business goals.',action:'Set measurable objectives, assumptions, resources, responsibilities, and review points.',signal:'Progress against objectives, resources, milestones, and financial assumptions.',scenario:'A project consumes resources without clear results, so reconnect activities to measurable business objectives.'},
  {t:'Budgeting',what:'Estimating and controlling the financial resources required for a project or business activity.',why:'Budget visibility supports responsible resource decisions.',action:'Estimate costs, document assumptions, monitor actuals, and investigate variances.',signal:'Budget, actual cost, forecast, and variance.',scenario:'Actual spending exceeds the plan, so analyze the variance and update the forecast or corrective action.'},
  {t:'Quality Management',what:'Planning and controlling processes so deliverables meet defined requirements and standards.',why:'Quality reduces defects and improves whether outputs meet expectations.',action:'Define acceptance criteria, prevent defects, inspect results, and improve processes.',signal:'Defects, rework, acceptance results, and quality measures.',scenario:'A deliverable fails acceptance, so identify the requirement missed and correct the process as well as the output.'},
  {t:'Team Leadership',what:'Guiding people toward shared objectives through direction, support, communication, and accountability.',why:'Effective coordination helps teams work toward common results.',action:'Clarify roles, remove obstacles, communicate expectations, and support constructive feedback.',signal:'Team progress, collaboration, unresolved blockers, and delivery against commitments.',scenario:'Two team members have conflicting responsibilities, so clarify ownership and agree on how work will be coordinated.'},
  {t:'Change Management',what:'A structured approach to assessing, approving, communicating, and implementing changes.',why:'Controlled change protects objectives while allowing justified adjustments.',action:'Assess impact, obtain appropriate approval, communicate the change, and update plans.',signal:'Change requests, approval status, impacts, and implementation progress.',scenario:'A requested change affects cost and schedule, so assess those impacts before approving it.'}
 ],
 gdm:[
  {t:'Color Psychology',what:'The study of how color choices can influence perception, emotion, and communication.',why:'Color can support the intended mood and meaning of a design.',action:'Choose a palette that fits the brand, audience, context, and accessibility needs.',signal:'Visual consistency, contrast, audience response, and brand recognition.',scenario:'A financial brand looks playful when it needs trust, so reconsider its palette and visual context.'},
  {t:'Typography',what:'The selection and arrangement of type to make written communication clear and expressive.',why:'Typography strongly affects readability, hierarchy, and visual personality.',action:'Use a limited, compatible type system with clear hierarchy and readable sizing.',signal:'Readability, hierarchy, consistency, and legibility across devices.',scenario:'A poster is difficult to scan, so strengthen heading hierarchy and body-text readability.'},
  {t:'Logo Branding',what:'Creating a distinctive visual mark that represents a brand identity.',why:'A recognizable mark can support consistent brand identification.',action:'Design a simple, distinctive mark that works at relevant sizes and contexts.',signal:'Recognition, consistency, scalability, and reproduction quality.',scenario:'A logo becomes unreadable at small size, so simplify details and test multiple sizes.'},
  {t:'Layout',what:'The arrangement of visual elements within a design space.',why:'Good layout guides attention and creates clear relationships among elements.',action:'Use alignment, spacing, hierarchy, grids, and balance to organize information.',signal:'Visual flow, alignment, spacing consistency, and ease of scanning.',scenario:'Important information is overlooked, so revise hierarchy and placement rather than adding more decoration.'},
  {t:'Visual Hierarchy',what:'The ordering of visual elements so viewers understand importance and reading sequence.',why:'It helps audiences identify the most important information quickly.',action:'Use size, contrast, position, spacing, and typography to establish priority.',signal:'Whether viewers notice and understand key information in the intended order.',scenario:'A minor detail dominates a poster, so reduce its visual weight and strengthen the main message.'},
  {t:'Brand Guidelines',what:'Rules that define consistent use of a brand’s visual identity and assets.',why:'Consistency helps different materials look and feel like the same brand.',action:'Document approved colors, fonts, logo use, imagery, spacing, and examples.',signal:'Consistency across channels and correct use of approved assets.',scenario:'Different teams use different logo versions, so provide clear usage rules and approved assets.'},
  {t:'Image Composition',what:'The deliberate arrangement of subjects, space, lines, and visual elements within an image.',why:'Composition directs attention and affects visual balance.',action:'Use framing, focal points, negative space, and alignment intentionally.',signal:'Focal clarity, balance, visual flow, and subject emphasis.',scenario:'A product is lost in a busy image, so simplify the background and strengthen the focal point.'},
  {t:'Design Principles',what:'Foundational concepts such as balance, contrast, alignment, repetition, and proximity.',why:'Principles provide a structure for making visual decisions coherent.',action:'Apply principles according to the communication goal rather than adding effects randomly.',signal:'Consistency, balance, contrast, grouping, and overall clarity.',scenario:'A design feels chaotic, so inspect alignment, grouping, repetition, and contrast systematically.'},
  {t:'Print Design',what:'Designing visual materials for physical reproduction such as posters, brochures, and cards.',why:'Print requires attention to physical size, resolution, color, margins, and production constraints.',action:'Set correct dimensions, resolution, color settings, bleed, and safe areas for the printer.',signal:'Print dimensions, image quality, color output, bleed, and proof results.',scenario:'Important text is cut off in a printed piece, so check safe margins and bleed before final export.'},
  {t:'Digital Design Tools',what:'Software features used to create, edit, arrange, and export digital visual assets.',why:'Tools enable efficient production and controlled editing of designs.',action:'Use appropriate layers, vectors, components, guides, and export settings for the task.',signal:'File organization, editability, export quality, and production efficiency.',scenario:'A design must be resized repeatedly, so use scalable elements and organized source files.'}
 ],
 fme:[
  {t:'Cash Flow',what:'The movement of cash into and out of a business during a period.',why:'Cash availability affects the ability to pay obligations when due.',action:'Track expected receipts and payments and monitor timing differences.',signal:'Operating cash inflows, outflows, and net cash movement.',scenario:'Sales are strong but bills cannot be paid on time, so examine the timing of cash inflows and outflows.'},
  {t:'Break-Even Analysis',what:'An analysis of the sales level at which total revenue equals total costs.',why:'It shows the activity needed to cover costs before generating operating profit.',action:'Separate fixed and variable costs and calculate the required sales volume or revenue.',signal:'Break-even units, break-even revenue, contribution margin, and margin of safety.',scenario:'A new product has high fixed costs, so calculate break-even before setting a sales target.'},
  {t:'Balance Sheets',what:'Financial statements showing assets, liabilities, and equity at a point in time.',why:'They provide a snapshot of financial position.',action:'Review the relationship among assets, liabilities, and equity and investigate material changes.',signal:'Asset, liability, equity, and liquidity measures.',scenario:'Liabilities rise sharply, so compare the balance sheet with prior periods and identify the source of the change.'},
  {t:'Income Statements',what:'Financial statements summarizing revenue, expenses, and profit or loss over a period.',why:'They show operating performance for the period.',action:'Analyze revenue, cost categories, margins, and profit against expectations or prior periods.',signal:'Revenue, gross profit, operating expenses, and net profit or loss.',scenario:'Revenue increases while profit falls, so examine cost growth and margins rather than looking at revenue alone.'},
  {t:'Financial Ratios',what:'Calculated relationships between financial statement figures used to evaluate performance or position.',why:'Ratios help compare financial conditions across periods or businesses.',action:'Select ratios appropriate to the decision and interpret them with context and trends.',signal:'Liquidity, profitability, leverage, and efficiency ratios.',scenario:'A liquidity ratio declines, so examine current assets and liabilities and the trend before drawing conclusions.'},
  {t:'Working Capital',what:'The difference between current assets and current liabilities.',why:'It indicates short-term resources available to support operations.',action:'Monitor receivables, inventory, cash, and payables to manage short-term funding needs.',signal:'Working-capital balance, current ratio, collection time, and payment timing.',scenario:'Customers pay slowly while suppliers require quick payment, so review receivables and payable timing.'},
  {t:'Budgeting',what:'Planning expected income, expenses, and resource use for a future period.',why:'Budgets provide a financial plan against which actual results can be monitored.',action:'Build realistic assumptions, assign responsibility, and compare actual results with the budget.',signal:'Budget versus actual results and variance explanations.',scenario:'A department repeatedly exceeds its budget, so investigate the assumptions and spending drivers.'},
  {t:'Cost Control',what:'Managing costs while maintaining the required level of quality and business performance.',why:'Uncontrolled costs can reduce margins and cash available for growth.',action:'Track cost drivers, investigate significant variances, and remove avoidable waste.',signal:'Unit cost, total cost, gross margin, and cost variances.',scenario:'Unit costs rise without a change in output quality, so investigate the drivers before accepting the increase.'},
  {t:'Investment Basics',what:'Evaluating the expected return, risk, timing, and resources involved in an investment.',why:'Investment decisions commit resources and involve uncertainty.',action:'Compare expected cash flows and risks with the investment objective and alternatives.',signal:'Expected return, cash flows, payback, and risk measures appropriate to the decision.',scenario:'Two investments have similar returns but different risk, so evaluate risk and timing rather than return alone.'},
  {t:'Entrepreneurial Finance',what:'Managing financial decisions and resources in a new or growing business.',why:'Entrepreneurs need to balance growth, cash needs, risk, and funding choices.',action:'Forecast cash needs, monitor unit economics, and choose financing consistent with the business stage.',signal:'Cash runway, margins, customer economics, funding needs, and growth performance.',scenario:'A fast-growing business is short of cash, so forecast cash requirements and funding timing before expansion.'}
 ],
 dbi:[
  {t:'SQL',what:'A language used to query and manipulate data in relational databases.',why:'It allows analysts to retrieve, filter, combine, and summarize structured data.',action:'Use appropriate SELECT, filtering, joins, grouping, and aggregation for the question.',signal:'Query correctness, result accuracy, execution time, and data completeness.',scenario:'A report double-counts customers after a join, so inspect the join relationship and grain of each table.'},
  {t:'Excel',what:'A spreadsheet tool used for calculation, organization, analysis, and visualization of data.',why:'It supports practical analysis and reporting for many business datasets.',action:'Use structured tables, formulas, validation, and appropriate analytical functions.',signal:'Formula correctness, data consistency, error checks, and reproducible calculations.',scenario:'A total changes unexpectedly, so inspect formulas, references, and source data rather than overwriting the result.'},
  {t:'Power BI',what:'A business intelligence platform for modeling, analyzing, and visualizing data.',why:'It helps users explore data and share interactive reports and dashboards.',action:'Build a suitable data model, define measures, and design visuals around business questions.',signal:'Data refresh status, model accuracy, measure results, and report usage.',scenario:'A dashboard shows inconsistent totals, so check the model relationships and measures before changing the visuals.'},
  {t:'Data Cleaning',what:'Identifying and correcting or handling inaccurate, inconsistent, incomplete, or duplicate data.',why:'Poor-quality data can produce misleading analysis.',action:'Profile data, define quality rules, handle missing values, duplicates, and invalid formats.',signal:'Completeness, validity, uniqueness, consistency, and error rates.',scenario:'A customer table contains duplicate records, so identify the duplicate rule and resolve records before analysis.'},
  {t:'Data Visualization',what:'Representing data graphically to communicate patterns, comparisons, and trends.',why:'Good visuals can make important information easier to understand.',action:'Choose a chart based on the analytical question and use clear labels and appropriate scales.',signal:'Clarity, accuracy, readability, and whether the visual supports the intended question.',scenario:'A line chart is used for unrelated categories, so select a chart type that better matches the comparison.'},
  {t:'Descriptive Statistics',what:'Methods that summarize the main characteristics of observed data.',why:'Summary statistics help analysts understand distributions and central tendencies.',action:'Use measures such as mean, median, range, and standard deviation appropriately.',signal:'Central tendency, spread, counts, percentiles, and distribution summaries.',scenario:'A few extreme values distort the mean, so compare it with the median and inspect the distribution.'},
  {t:'Data Storytelling',what:'Communicating analysis as a clear narrative connecting evidence to a business question.',why:'A story helps decision-makers understand what the data means and what action may follow.',action:'Start with the decision question, present relevant evidence, explain implications, and state limitations.',signal:'Audience comprehension, relevance, evidence quality, and clarity of the recommended next step.',scenario:'A dashboard contains many charts but no conclusion, so organize the analysis around the decision the audience must make.'},
  {t:'Business Intelligence',what:'Using data, analysis, and reporting to support informed business decisions.',why:'BI connects operational data with questions about performance and action.',action:'Define decision needs, integrate reliable data, analyze results, and deliver useful reports.',signal:'Accuracy, timeliness, adoption, and decision-relevant insights.',scenario:'Managers receive a report too late to act, so improve data refresh and delivery timing.'},
  {t:'Data Privacy',what:'Protecting personal or sensitive information through appropriate collection, use, access, and handling.',why:'Responsible data use reduces privacy risks and supports trust and compliance.',action:'Collect only needed data, restrict access, protect it, and follow applicable privacy requirements.',signal:'Access controls, data handling practices, retention, incidents, and compliance checks.',scenario:'A report exposes unnecessary personal fields, so remove or restrict fields that are not needed for the analysis.'},
  {t:'Predictive Analytics',what:'Using historical and current data with statistical or machine-learning methods to estimate future outcomes.',why:'Predictions can support planning and prioritization when uncertainty is acknowledged.',action:'Define the target, prepare representative data, validate the model, and monitor performance.',signal:'Prediction error, validation results, calibration, drift, and business usefulness.',scenario:'A model performs well initially but degrades later, so check for data or behavior changes and monitor drift.'}
 ]
};

(function(){
 const typeKeys=['what','why','action','signal','scenario'];
 function make(course){
  const rows=window.EDSA_QUESTION_BANKS[course]||[];
  const out=[];
  rows.forEach((r,i)=>typeKeys.forEach((k,j)=>{
   const labels={what:'What is the main idea of',why:'Why is',action:'Which practice is most appropriate for',signal:'Which evidence or measure is most useful for monitoring',scenario:'What is the most appropriate response when managing'};
   const text=j===0?`${labels[k]} ${r.t}?`:j===1?`${labels[k]} ${r.t}?`:j===2?`${labels[k]} ${r.t}?`:j===3?`${labels[k]} ${r.t}?`:`${labels[k]} ${r.t}?`;
   const wrong=[];
   for(let n=1;wrong.length<3;n++){const other=rows[(i+n)%rows.length][k];if(other!==r[k]&&!wrong.includes(other))wrong.push(other)}
   out.push({q:text,options:[r[k],...wrong],correct:0});
  }));
  return out;
 }
 ['dme','pbm','gdm','fme','dbi'].forEach(c=>window.EDSA_QUESTION_BANKS[c]=make(c));
})();
